name: Deploy PSD Generator

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ここで「tools/AnimPSD」に移動して作業します
      - name: Install and Build
        run: |
          cd tools/AnimPSD
          npm install
          npm run build

      # ビルド後のdistフォルダをGitHub Pagesが認識する場所へ移動
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'tools/AnimPSD/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
